### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by jdeschamps** [imagej/imagej-modelzoo#9]
Updating imglib2-cache (v1.0.0-beta-16) from the Fiji update site causes a NoClassDefFoundError in TiledImageDataReference.createTiledOutputView. Compiling against version 30.0.0 of the scijava-pom made the error disappear (but there are JUnit test failures that I did not investigate).

```
java.lang.NoClassDefFoundError: net/imglib2/cache/img/DiskCachedCellImgOptions$CacheType
	at net.imagej.modelzoo.consumer.tiling.TiledImageDataReference.createTiledOutputView(TiledImageDataReference.java:204)
	at net.imagej.modelzoo.consumer.tiling.TiledImageDataReference.createTiledOutputView(TiledImageDataReference.java:163)
	at net.imagej.modelzoo.consumer.tiling.DefaultTiling.init(DefaultTiling.java:105)
	at net.imagej.modelzoo.consumer.TiledPredictionExecutor.initTiling(TiledPredictionExecutor.java:188)
	at net.imagej.modelzoo.consumer.TiledPredictionExecutor.run(TiledPredictionExecutor.java:84)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.executePrediction(AbstractModelZooPrediction.java:210)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.run(AbstractModelZooPrediction.java:105)
	at net.imagej.modelzoo.consumer.command.AbstractSingleImagePredictionCommand.run(AbstractSingleImagePredictionCommand.java:101)
	at de.csbdresden.n2v.command.N2VPredictCommand.run(N2VPredictCommand.java:59)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.imglib2.cache.img.DiskCachedCellImgOptions$CacheType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

This was reported in a [N2V_fiji issue](https://github.com/juglab/N2V_fiji/issues/28).

**Comment by jdeschamps** [comment]
Fixed for release 0.9.9!
